right_edge_stop_enabled: true
table_output_enabled: false
test_task: false
method: 'rkMerson' #rk2, rkMerson
p: 4 #p : 2, 4

#calc params
Xend: 100 #правая граница
XendEps: 0.001 #Epsilon граничный

Nmax: 10000 #максимальное число шагов
eps: 0.00001 #параметр контроля ЛП
hn: 0.01 #начальный шаг

#начальные условия
x0: 0.0
w0: 1.0
phi0: 1.0
phi_0: 1.2 #производная phi

#параметры задачи
k: 1.0
m: 1.0
n: 0.01
F: 1
J: 3.0
g: 1.0
b: 1